### ISSUE TITLE
Add uniqueness constraint on environment name

### ISSUE THREAD

**Issue by abodelot** [abodelot/varager#7]

**Comment by ant31** [comment]
What about having name composed with parents's name?

|-App1
   |-> Prod
|-App2
   |-> Prod

the 'full-names' would be :
app1-prod and app2-prod

In short uniqueness on name+ancestor

**Comment by abodelot** [comment]
But there will be also a default app at top level, this can leads to long name and a lack of customization.

Also, if the name is used as an identifier (url slug), it's better to have the field as-is in database so can still fetch the item with a single query.

**Comment by ant31** [comment]
why default app?
